-- 코드를 작성해주세요
SELECT II.ITEM_ID, II.ITEM_NAME, II.RARITY FROM ITEM_INFO II 
INNER JOIN  
(SELECT ITEM_ID FROM ITEM_TREE
WHERE PARENT_ITEM_ID IN (SELECT ITEM_ID FROM ITEM_INFO WHERE RARITY = 'RARE')
) IT
ON IT.ITEM_ID = II.ITEM_ID
ORDER BY ITEM_ID DESC