-- 코드를 작성해주세요
SELECT DISTINCT DS.ID, DS.EMAIL, DS.FIRST_NAME, DS.LAST_NAME FROM DEVELOPERS DS
, (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python' OR NAME = 'C#') AS SC
WHERE DS.SKILL_CODE & SC.CODE != 0
ORDER BY ID