-- 코드를 작성해주세요
SELECT M.YEAR AS YEAR, ABS(ED.SIZE_OF_COLONY - M.MAXCOL) AS YEAR_DEV, ED.ID FROM ECOLI_DATA AS ED 
INNER JOIN 
(SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAXCOL 
 FROM ECOLI_DATA 
 GROUP BY YEAR(DIFFERENTIATION_DATE)) AS M
 ON YEAR(DIFFERENTIATION_DATE) = M.YEAR
 ORDER BY YEAR, YEAR_DEV